### PR TITLE
Fix: make horizontal padding align across the page

### PR DESCRIPTION
**Pull request by teoh4770**
Issue: #162 
Branch: fix/157/horizontal-padding-seems-not-align-in-every-section

Note: 
1. I have remove the styling in a part of the hero section, since I have another pr that's gonna merge a new styling to it
2. I didn't change the sponsors, since it's gonna have a major change (will have horizontal scrollbars)

### CODE REVIEW

**Comment by aidantrabs** [comment]
- 1500px width

Screenshot 2024-03-26 at 11 35 44 PM

Screenshot 2024-03-26 at 11 36 17 PM

**Comment by teoh4770** [comment]
@aidantrabs ^
- I have remove the styling in a part of the hero section, since I have another pr that's gonna merge a new styling to it
- for the faq one, can we make a pr for that, since it is using flexbox to style, instead of grid?

**Comment by teoh4770** [comment]
@aidantrabs fixed. Ready for review

**Review by GabeDiniz — APPROVED** [review]

**Comment by aidantrabs** [comment]
Fix conflicts and then merge

**Pull request merged**
