### PR TITLE
Feature/133/merge hero section with stats section

### PR DESCRIPTION
**Pull request by GabeDiniz**
✨ **Issue:** https://github.com/LaurierHawkHacks/Landing/issues/133
🔀 **Branch:** feature/33/merge-hero-section-with-stats-section

**✏ What was changed?**
- Merge Hero and About section
- Removed the unnecessary files

SOMEONE HELP... I don't know why this is throwing an error.
image

### CODE REVIEW

**Comment by teoh4770** [comment]
Will look into it on Friday

**Comment by teoh4770** [comment]
It's a busy week 😔

**Comment by teoh4770** [comment]
But you may list out the things you have already tried here

**Comment by GabeDiniz** [comment]
Sounds good! Its just importing/exporting the HeroStatsSection, but for some reason its not recognizing it as an export and I know its just gonna be something stupid..

**Comment by AmirAgassi** [comment]
> Sounds good! Its just importing/exporting the HeroStatsSection, but for some reason its not recognizing it as an export and I know its just gonna be something stupid..

Yup, sadly 😭 

The issue is just a mix up between default and named exports, HeroStatsSection is exported as a default but it should be exported as a named export instead.

**Comment by GabeDiniz** [comment]
BRO I knew it was something stupid.. thanks Amir!

**Pull request merged**
