### PR TITLE
Feature: move dashboard button to landing

### PR DESCRIPTION
**Pull request by teoh4770**
Issue: https://github.com/LaurierHawkHacks/Landing/issues/120

Two things:
1. Import the most impressive button component I have seen
2. Update the existing button to button component that @juancwu created.

### CODE REVIEW

**Comment by teoh4770** [comment]
@juancwu any reason you setup this in tailwind.config if you don't use it?
```js
'tbrand-mouse-down': '#1D7882',
'tbrand-highlight': '#00CEDB',
```

**Review by juancwu — APPROVED** [review]

**Comment by teoh4770** [comment]
Btw...it's not passing the automated check for some reason. Might need help on this one >:D

```
Warning: CodeQL Action v2 will be deprecated on December 5th, 2024. Please update all occurrences of the CodeQL Action in your workflow files to v3. For more information, see https://github.blog/changelog/2024-01-12-code-scanning-deprecation-of-codeql-action-v2/
Error: Path does not exist: eslint-results.sarif
ConfigurationError: Path does not exist: eslint-results.sarif
    at run (/home/runner/work/_actions/github/codeql-action/v2/lib/upload-sarif-action.js:65:15)
    at async runWrapper (/home/runner/work/_actions/github/codeql-action/v2/lib/upload-sarif-action.js:76:[9](https://github.com/LaurierHawkHacks/Landing/actions/runs/8127235652/job/22211846750?pr=122#step:5:10))
 ```

**Comment by juancwu** [comment]
> @juancwu any reason you setup this in tailwind.config if you don't use it?
> 
> ```js
> 'tbrand-mouse-down': '#1D7882',
> 'tbrand-highlight': '#00CEDB',
> ```

Did not make a whole lot sense when the colours are not widely shared so I just put in the arbitrary colours in the component. Left the styles cuz I forgot to remove them lol.

**Comment by juancwu** [comment]
> Btw...it's not passing the automated check for some reason. Might need help on this one >:D
> 
> ```
> Warning: CodeQL Action v2 will be deprecated on December 5th, 2024. Please update all occurrences of the CodeQL Action in your workflow files to v3. For more information, see https://github.blog/changelog/2024-01-12-code-scanning-deprecation-of-codeql-action-v2/
> Error: Path does not exist: eslint-results.sarif
> ConfigurationError: Path does not exist: eslint-results.sarif
>     at run (/home/runner/work/_actions/github/codeql-action/v2/lib/upload-sarif-action.js:65:15)
>     at async runWrapper (/home/runner/work/_actions/github/codeql-action/v2/lib/upload-sarif-action.js:76:[9](https://github.com/LaurierHawkHacks/Landing/actions/runs/8127235652/job/22211846750?pr=122#step:5:10))
> ```

I think its good to learn some DevOps @teoh4770 :eyes:

**Comment by teoh4770** [comment]
> > @juancwu any reason you setup this in tailwind.config if you don't use it?
> > ```js
> > 'tbrand-mouse-down': '#1D7882',
> > 'tbrand-highlight': '#00CEDB',
> > ```
> 
> Did not make a whole lot sense when the colours are not widely shared so I just put in the arbitrary colours in the component. Left the styles cuz I forgot to remove them lol.

Solid reason lmao.

**Comment by teoh4770** [comment]
> > Btw...it's not passing the automated check for some reason. Might need help on this one >:D
> > ```
> > Warning: CodeQL Action v2 will be deprecated on December 5th, 2024. Please update all occurrences of the CodeQL Action in your workflow files to v3. For more information, see https://github.blog/changelog/2024-01-12-code-scanning-deprecation-of-codeql-action-v2/
> > Error: Path does not exist: eslint-results.sarif
> > ConfigurationError: Path does not exist: eslint-results.sarif
> >     at run (/home/runner/work/_actions/github/codeql-action/v2/lib/upload-sarif-action.js:65:15)
> >     at async runWrapper (/home/runner/work/_actions/github/codeql-action/v2/lib/upload-sarif-action.js:76:[9](https://github.com/LaurierHawkHacks/Landing/actions/runs/8127235652/job/22211846750?pr=122#step:5:10))
> > ```
> 
> I think its good to learn some DevOps @teoh4770 👀

Can't avoid devop 😭

**Comment by juancwu** [comment]
> > > Btw...it's not passing the automated check for some reason. Might need help on this one >:D
> > > ```
> > > Warning: CodeQL Action v2 will be deprecated on December 5th, 2024. Please update all occurrences of the CodeQL Action in your workflow files to v3. For more information, see https://github.blog/changelog/2024-01-12-code-scanning-deprecation-of-codeql-action-v2/
> > > Error: Path does not exist: eslint-results.sarif
> > > ConfigurationError: Path does not exist: eslint-results.sarif
> > >     at run (/home/runner/work/_actions/github/codeql-action/v2/lib/upload-sarif-action.js:65:15)
> > >     at async runWrapper (/home/runner/work/_actions/github/codeql-action/v2/lib/upload-sarif-action.js:76:[9](https://github.com/LaurierHawkHacks/Landing/actions/runs/8127235652/job/22211846750?pr=122#step:5:10))
> > > ```
> > 
> > 
> > I think its good to learn some DevOps @teoh4770 👀
> 
> Can't avoid DevOps 😭

Next time you can just run `pnpm run lint` to check for issues when its the eslint action.

I have updated the PR with the changes needed.

**Comment by teoh4770** [comment]
> > > > Btw...it's not passing the automated check for some reason. Might need help on this one >:D
> > > > ```
> > > > Warning: CodeQL Action v2 will be deprecated on December 5th, 2024. Please update all occurrences of the CodeQL Action in your workflow files to v3. For more information, see https://github.blog/changelog/2024-01-12-code-scanning-deprecation-of-codeql-action-v2/
> > > > Error: Path does not exist: eslint-results.sarif
> > > > ConfigurationError: Path does not exist: eslint-results.sarif
> > > >     at run (/home/runner/work/_actions/github/codeql-action/v2/lib/upload-sarif-action.js:65:15)
> > > >     at async runWrapper (/home/runner/work/_actions/github/codeql-action/v2/lib/upload-sarif-action.js:76:[9](https://github.com/LaurierHawkHacks/Landing/actions/runs/8127235652/job/22211846750?pr=122#step:5:10))
> > > > ```
> > > 
> > > 
> > > I think its good to learn some DevOps @teoh4770 👀
> > 
> > 
> > Can't avoid DevOps 😭
> 
> Next time you can just run `pnpm run lint` to check for issues when its the eslint action.
> 
> I have updated the PR with the changes needed.

Noted

**Comment by juancwu** [comment]
Merge so that new branches can use the button component.

**Pull request merged**
