### PR TITLE
Feature/53/add loading animation

### PR DESCRIPTION
**Pull request by GabeDiniz**
Created the loading animation component. Right now, the component appears for 3 seconds, then loads the Landing page. I know this isn't great practice, so would you guys rather I remove the useEffect/useState that displays the loader? That way the **Loader** component is ready for use in the future?

Engineering Discord channel shows what the current state of the loader looks like.

### CODE REVIEW

**Comment by juancwu** [comment]
I don't think we need it right since we don't do any many data queries in the background. It seems you have it setup as a global show/hide but I would think a more granular skeleton loading for a piece of component that is loading data will be more useful. If the whole page is blocked by a slow component that is loading data, it is annoying to wait for that one part.

**Comment by GabeDiniz** [comment]
Yup, that makes way more sense. Should I update the code so that only the Loader component is present? That way, we can add the Loader to other components in the future if need be or is there something else you had in mind? Just want to get some clarity on this :)

**Comment by juancwu** [comment]
@GabeDiniz I think we should have the loader component as a separate file and when needed we can put it to use.

**Review by juancwu — CHANGES_REQUESTED** [review]
Remove loader component from landing page but do not delete the loader component file.

**Comment by GabeDiniz** [comment]
@juancwu that's exactly what I had in mind :). I made some changes, can you take a look when you get a chance? 💯

**Review by juancwu — APPROVED** [review]
lgtm!

**Pull request merged**
