### PR TITLE
Feature: Add Tailwind Theme

### PR DESCRIPTION
**Pull request by teoh4770**
Issue: https://github.com/LaurierHawkHacks/Landing/issues/100

If there's more styles need to add in the config, write your suggestions at the comment below.

### Changes compare to previous tailwind config

**Font**

- Only font family "Raleway" is used
- font weight 600 is the most common across the design

**Color**

- mix of beige, purple, blue, yellow and gray
- most of the colors are from the illustration actually

### Code Changed

```
...
fontFamily: {
                sans: ['"Raleway"', ...defaultTheme.fontFamily.sans],
            },
            colors: {
                peachPuff: '#FDDDB7',
                eggShell: '#F1E7DF',
                dustStorm: '#EBCACC',
                brightUbe: '#CBAAF4',
                paleViolet: '#BAA3FA',
                blueGreen: '#0FA3B1',
                cadetBlue: '#0C6975',
                slateGray: '#31495C',
                copper: '#DE846E',
                khakiYellow: '#F0E698',
                dimGray: '#4A4F50',
            },
...
```

### CODE REVIEW

**Review by aidantrabs — APPROVED** [review]
looks good to me

only thing i would add is to override all the font sizes and make sure they match with the figma (sm, md, lg, xl)

**Comment by teoh4770** [comment]
Ok, let me update it later

**Comment by teoh4770** [comment]
let me know if the font size setting is good now 👍

**Comment by juancwu** [comment]
not reviewing smh

**Pull request merged**
