### PR TITLE
Fix: improve performance

### PR DESCRIPTION
**Pull request by teoh4770**
Issue: #264 
Branch: [fix/264/performance-issue](https://github.com/LaurierHawkHacks/Landing/compare/main...fix/264/performance-issue?expand=1)

What this pr do:
[fix: accessibility score improve from 80 to 96](https://github.com/LaurierHawkHacks/Landing/commit/cd6bca29402966daaf65e1d1b8f582d5df7a181d)
[fix: clean up unused assets](https://github.com/LaurierHawkHacks/Landing/commit/7fb02e34720ca8046289eeccdd00c0836719d007)
[fix: minimize a few images + preload some important images + lazy loa…](https://github.com/LaurierHawkHacks/Landing/commit/d99f73c5173a244e837b28244d8b4dc141e4e005)

Note1: I have only slightly optimize some of the assets and indicate the browser to preload and lazy load some of the resources. 
Note2: I realize there's a layout shift in the landing page, which i gonna fix first

### CODE REVIEW

**Review by GabeDiniz — APPROVED** [review]
W Chee, we really needed this clean up

**Comment by aidantrabs** [comment]
Fix merge conflicts and then you should be good to go

**Comment by teoh4770** [comment]
Yup will do it 👍

**Comment by teoh4770** [comment]
I got an error in the dependabot.yml file. 
```- package-ecosystem: "pnpm" #```
I update this line to 
```- package-ecosystem: "npm" #```
https://github.com/LaurierHawkHacks/Landing/pull/278/commits/c3ad8950f51899f5964825da4815515bf8e85fe3

**Comment by teoh4770** [comment]
@aidantrabs merge conflict is clear now

**Pull request merged**
