### PR TITLE
Fix: good birdy at contact

### PR DESCRIPTION
**Pull request by teoh4770**
Issue: #172 
Branch: fix/172/distorted-birdy-at-contact

### CODE REVIEW

**Comment by aidantrabs** [comment]
pretty sure its still broken between 720px and 760px 

what's wrong with the version on main?

**Comment by teoh4770** [comment]
Overflow

**Comment by teoh4770** [comment]
Can you take a screenshot of that at 720px? @aidantrabs

**Comment by teoh4770** [comment]
I didn't find it broken though @aidantrabs

**Comment by GabeDiniz** [comment]
The bird isn't distorted for me at any width.. weird that its distorted for Aidan. 
740px width:
image

**Review by GabeDiniz — APPROVED** [review]

**Pull request merged**
