### PR TITLE
Bug/280/fix faq section issues

### PR DESCRIPTION
**Pull request by GabeDiniz**
✨ **Issue:** https://github.com/LaurierHawkHacks/Landing/issues/280
🔀 **Branch:** bug/280/fix faq section issues

**✏ What was changed?**
- Updated all FAQs to match Notion
- Decreased spacing for paragraphs in FAQ

**📜 Things to know**
@SherRao the "I'm lost!..." answer, in the notion you have an embedded link for the Google Map directions. I couldn't find an easy way to do this. I was able to do it in a _sketchy_ way using  ```dangerouslySetInnerHTML={{ __html: line }}``` and some conditionals inside fo the accordion. 

For now, I just removed the line that says "Google Map directions can be found here".

### CODE REVIEW

**Comment by SherRao** [comment]
Can we not have <a> tags inside of the paragraphs? there's a few hyperlinks we should have

**Review by SherRao — CHANGES_REQUESTED** [review]
Can we not have tags inside of the paragraphs? there's a few hyperlinks we should have

**Comment by GabeDiniz** [comment]
> Can we not have tags inside of the paragraphs? there's a few hyperlinks we should have

@SherRao no :( it gets read as text unfortunately. I tried searching it up and all I found was the dangerouslySetInnerHTML={{ __html: line }} solution. Given the name, pretty sure its not a good idea XD

**Comment by teoh4770** [comment]
I agree with @SherRao regarding the tags, personally feel that links should appear in the faq though :))

**Comment by SherRao** [comment]
> > Can we not have tags inside of the paragraphs? there's a few hyperlinks we should have
> 
> @SherRao no :( it gets read as text unfortunately. I tried searching it up and all I found was the dangerouslySetInnerHTML={{ __html: line }} solution. Given the name, pretty sure its not a good idea XD

I give you my blessing and permission to use `dangerouslySetInnerHTML`.

**Comment by GabeDiniz** [comment]
@SherRao it's not pretty bro.. but it works.

**Review by SherRao — CHANGES_REQUESTED** [review]
Can we hyperlink the two Discord channels mentioned, and hyperlink the contact email using `mailto`?

**Pull request merged**
