### PR TITLE
Enhancement/265/Redo-FAQ-section-with-new-styling

### PR DESCRIPTION
**Pull request by ABCodez**
image
image

### CODE REVIEW

**Comment by teoh4770** [comment]
@ABCodez 
1. I believe the buttons can be smaller in the mobile view, so that they are not taking too much space
2. also, try to make the accordion item text left align, somehow when the text break into another line, the text shift as well
3. can you try to remove the accordion card expand transition, it is the main reason why it felt janky

**Comment by ABCodez** [comment]
@teoh4770, I made a few changes based on ur feedback ! Everything should look a bit more cleaned up + smaller on mobile. The categories section still looks a bit big on mobile, the original design had it be an accordion as well but, I feel like that'd just be too much lol. 

Check it out tho, and lmk what ya think :)

**Comment by teoh4770** [comment]
@ABCodez is better now for sure, but you can make them more consistent. You can improve the tab section in mobile view, by making it smaller(than the accordion) and draw less attention. Keep the ratio between the tabs and the accordion in mobile view the same the desktop view.

Screenshot 2024-04-09 at 7 59 06 AM

Screenshot 2024-04-09 at 7 59 22 AM

**Comment by ABCodez** [comment]
New styling for FAQ

image
image

**Comment by teoh4770** [comment]
Way better than the OG one. But personally thought that the heading size is slightly bigger? You can refer to the other section's header to see if the size is aligned.

**Pull request merged**
