### PR TITLE
Bug/80/fix sponsor section overflow

### PR DESCRIPTION
**Pull request by GabeDiniz**
🛠️ [Fix Sponsor Section Overflow](https://github.com/LaurierHawkHacks/Landing/issues/80)

# 🔍 What's Included

Revised Sponsors.section.tsx and index.css.
### 📁 Files Affected:
src/components/sections/Sponsors.section.tsx
-> Reformatted code to match prettier format and made small Tailwind adjustments

src/index.css
-> Removed CSS code (wasn't doing much) and made small changes to the CSS sponsor-row class

Suggestion: add a noticeable divider between the 3 tiers so users can distinguish the tier of each section. 

# Large Screen
image

# Medium Screen
image

# Small Screen 
image

### CODE REVIEW

**Review by AmirAgassi — APPROVED** [review]
Looks great to me!
Definitely needed the refactoring as well.

**Comment by GabeDiniz** [comment]
@AmirAgassi hope you don't mind, I stole your PR comment formatting 😋

**Comment by AmirAgassi** [comment]
No worries at all! I'm glad you found it as cool as I did 🤣

**Comment by GabeDiniz** [comment]
@juancwu yea I totally agree, I feel like there needs to be a design discussion for the sponsor's section on Mobile. There needs to be a way to distinguish the different tiers.
Thanks though! I'll close it for now :)

**Pull request merged**
